### PR TITLE
changes in the cursor of heading from default to arrow and also chang…

### PR DESCRIPTION
**Pull request by sandeep0009**
…es in alignement f image where it is aligned with the heading of the project

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
I will merge this once i got approval from gssoc

**Comment by Vikash-8090-Yadav** [comment]
Hey bro thanks for this pr . Can u please  share the old as well as new pic . updated one and original one basically . 
Thank uh!

**Comment by sandeep0009** [comment]
image
this is old version

**Comment by sandeep0009** [comment]
image
new changes are made with image alignment and hovering effect image and title of project

**Comment by Vikash-8090-Yadav** [comment]
Great work @sandeep0009 . Looking forward to see more contribution from your side.

**Comment by Vikash-8090-Yadav** [comment]
Issue No : #31

**Pull request merged**
