### PR TITLE
Changed scrollbar css properties

### LINKED ISSUE #70: Improvement in UI by making several css changes
The changes are mostly related to  : 

Button : we can add color changing property when the button gets hovered upon. It makes the design look more modern.

scrollbar : adding css to the scrollbars to make the website look more pretty.

and many other small changes that can make the the UI better.

So if you want I would like to do the task.

And this is related to Gssoc'23

### PR DESCRIPTION
**Pull request by raghav1030**
Changed the css property for the scrollbar.
Closes #70

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Hey please  linked ur issue number .

**Comment by raghav1030** [comment]
I have linked the issue number in the first comment

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
