### PR TITLE
Fixed alignment of login buttons

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
# Issue
I have fixed alignment of the login buttons and centered them and reduced the margins

# Fixes Issue #184 

# Screenshots
image

Please merge this PR under GSSOC 23

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@Swapnil-Singh-99 please   share the image of the original as well. Thanks!

**Comment by Swapnil-Singh-99** [comment]
image
The buttons are too far apart doesn't look great

**Comment by Swapnil-Singh-99** [comment]
@Vikash-8090-Yadav I have also added justify center

**Comment by Vikash-8090-Yadav** [comment]
Great. Thanks!

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
