### PR TITLE
Design Buy Me Coffee

### PR DESCRIPTION
**Pull request by coder12git**
I have designed the "Buy Me Coffee" part, according to the designs provided!
Screenshot 2023-07-22 205137

Issue - #187

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Hey for small screen make this in the centre. Hope u get it. Let me know if  u are facing any issue. Thanks!

**Comment by coder12git** [comment]
> Hey for small screen make this in the centre. Hope u get it. Let me know if u are facing any issue. Thanks!

Hey, I am not able to do that, if you see for all components, this is common, I don't know why  but for screen size less than 768 px, the center property is not working. I tried my best.

**Comment by coder12git** [comment]
@Vikash-8090-Yadav did you check this?

**Comment by Vikash-8090-Yadav** [comment]
Hey @coder12git take  the refrence from this application https://github.com/Vikash-8090-Yadav/Portfolio_3.0  buy me coffee. If u are still facing any error or issue then let me know. Thanks!

**Comment by coder12git** [comment]
> Hey @coder12git take the refrence from this application https://github.com/Vikash-8090-Yadav/Portfolio_3.0 buy me coffee. If u are still facing any error or issue then let me know. Thanks!

@Vikash-8090-Yadav Woh align center is not working in your code for smaller screens, I tried your reference code also, it's not working in your project, there might be any issue in tailwind config. js file or global. css, bcoz I am doing everything right.
I tried my best to find out but seems like it's an issue that's happening bcoz of your project code that's applying globally which is preventing my code to do that behavior for smaller screen

**Pull request merged**
