### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
added badges #58

### CODE REVIEW

**Comment by Ayush-Tibrewal** [comment]
@Vikash-8090-Yadav please check

**Comment by Vikash-8090-Yadav** [comment]
Share  the ss of changed and older one.

**Comment by Ayush-Tibrewal** [comment]
new 
added badges which made readme more informative and appealing 
image
added method for the new contributors 
image



old one 
image
image
@Vikash-8090-Yadav

**Comment by Ayush-Tibrewal** [comment]
@Vikash-8090-Yadav please make it under gssoc before merge

**Comment by Vikash-8090-Yadav** [comment]
Great work @Ayush-Tibrewal

**Comment by Ayush-Tibrewal** [comment]
@Vikash-8090-Yadav there is 2 pull request for readme so merge according one of the contributor has update the readme after the merge

**Pull request merged**
