### PR TITLE
Fix Issue#159 Redesign the Footer

### PR DESCRIPTION
**Pull request by coder12git**
I have designed the footer according to the Design template.
Screenshot 2023-06-11 164835

### CODE REVIEW

**Comment by coder12git** [comment]
@Vikash-8090-Yadav I have designed the footer. Also, I have provided the screenshot of my work. Please review it!

**Comment by Vikash-8090-Yadav** [comment]
LGTM, SOON REVIEW THE RESPONSIVE. IF U Want TAKE ANOTHER FEATURE ISSUE

**Comment by coder12git** [comment]
Sure, so now I can work on other issue?

**Comment by coder12git** [comment]
Also, when it will final merge?

**Comment by Vikash-8090-Yadav** [comment]
https://www.figma.com/proto/iAFIUE69Xk45BV3WEi2ilR/Sal-Dapp?type=design&node-id=6-61&scaling=scale-down-width&page-id=6%3A59&starting-point-node-id=6%3A61

Open this in a private window, and make the Sall Dapp and Meta. Eth is slightly down. as shown in the Figma design. 
Thanks!

PS: Al things are good and Good to go for merge.

**Comment by Vikash-8090-Yadav** [comment]
> > https://www.figma.com/proto/iAFIUE69Xk45BV3WEi2ilR/Sal-Dapp?type=design&node-id=6-61&scaling=scale-down-width&page-id=6%3A59&starting-point-node-id=6%3A61
> > Open this in a private window, and make the Sall Dapp and Meta. Eth is slightly down. as shown in the Figma design. Thanks!
> > PS: Al things are good and Good to go for merge.
> 
> What do you mean by "make the Sall Dapp and Meta"?

I mean if possible then shift the Sall Dapp logo and the Meta.Eth slightly down  a/c to the design shared above. Let me know if u faces any  issue. Thanks!!

**Comment by coder12git** [comment]
> > > https://www.figma.com/proto/iAFIUE69Xk45BV3WEi2ilR/Sal-Dapp?type=design&node-id=6-61&scaling=scale-down-width&page-id=6%3A59&starting-point-node-id=6%3A61
> > > Open this in a private window, and make the Sall Dapp and Meta. Eth is slightly down. as shown in the Figma design. Thanks!
> > > PS: Al things are good and Good to go for merge.
> > 
> > 
> > What do you mean by "make the Sall Dapp and Meta"?
> 
> I mean if possible then shift the Sall Dapp logo and the Meta.Eth slightly down a/c to the design shared above. Let me know if u faces any issue. Thanks!!

@Vikash-8090-Yadav Done. Please review it!

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM, THANKS

**Comment by coder12git** [comment]
@Vikash-8090-Yadav my pr didn't get counted because you marked the wrong label.
it should be level3

Screenshot 2023-06-20 131332
Please change it.

**Pull request merged**
