### PR TITLE
[Docs] - Added a socials section and badges to that section in the readme

### LINKED ISSUE #199: [Docs] - Adding a socials section and badges to that section in the readme
### Category of documentation update

We should have a socials section in the readme. Example -

image

This would help you improve your project react and your social media profile as well.
Please assign me this issue under GSSoC'23

### Describe the change you think might work

added above

### PR DESCRIPTION
**Pull request by 1Shubham7**
Added a socials section and added badges to it.

Closes #199

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
instead of insta make for the mail `yadav621gzp@gmail.com`

**Comment by 1Shubham7** [comment]
done @Vikash-8090-Yadav Please check it out now

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Comment by 1Shubham7** [comment]
thank you

**Pull request merged**
