### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by sandeep0009**
before the input form and button were looking like this:
image

after making changes it looks like this
image

### CODE REVIEW

**Comment by sandeep0009** [comment]
image
even that form were having outline that is also removed

**Comment by Vikash-8090-Yadav** [comment]
Great work @sandeep0009 .

**Comment by Vikash-8090-Yadav** [comment]
is this same as this pr ? https://github.com/Vikash-8090-Yadav/SaL--dApp/pull/45

**Comment by sandeep0009** [comment]
bro u had assigned me this work and they had made pr even being worked assigned to me .and also i had made pr first than them

**Comment by Vikash-8090-Yadav** [comment]
@sandeep0009 can u please tag me there in which u see the duplication pr so that i can close those .

**Comment by Vikash-8090-Yadav** [comment]
Hey, bro @sandeep0009 please solve the subscribe overflow. 

Screenshot from 2023-05-22 19-50-00

**Comment by sandeep0009** [comment]
Okay I will do it by today

**Comment by sandeep0009** [comment]
bro im facing some error regarding some bugs because i was working on the other issues so can i fork new one and push a new pull request

**Comment by Vikash-8090-Yadav** [comment]
Sure,close this one and linked this pr.

**Pull request closed without merging**
