### PR TITLE
[feat]Redesign About section #179

### PR DESCRIPTION
**Pull request by coder12git**
I have redesigned the About section according to the designs provided!!

Screenshot 2023-07-15 232729

### CODE REVIEW

**Comment by coder12git** [comment]
@Vikash-8090-Yadav Please review it!

**Comment by Vikash-8090-Yadav** [comment]
Great work @coder12git. PLease see this as  well. 
Screenshot from 2023-07-16 19-52-12

**Comment by coder12git** [comment]
Okay, will make it responsive

**Comment by coder12git** [comment]
@Vikash-8090-Yadav Check now, try to make it responsive as much as possible by me.

**Comment by Vikash-8090-Yadav** [comment]
You can do one thing, for the smaller screen make the responsiveness to the flex col such that the image and the paragraph appear in parallel form one below the other just like as Hero section. This may improve the responsiveness more. 
Thanks!

**Comment by coder12git** [comment]
> You can do one thing, for the smaller screen make the responsiveness to the flex col such that the image and the paragraph appear in parallel form one below the other just like as Hero section. This may improve the responsiveness more. Thanks!

Screenshot 2023-07-17 213749
Done as you said!!

**Comment by coder12git** [comment]
@Vikash-8090-Yadav Review this asap

**Pull request merged**
