### PR TITLE
Fixed a minor grammatical mistake

### PR DESCRIPTION
**Pull request by Chinmay-Deo-2004**
Changed "Oh! You stucked? Dont worry" to "Oh, you're stuck? Don't worry," in the Contact.js component.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Great issue . but i ll suggest to raise an issue for this first

**Comment by Vikash-8090-Yadav** [comment]
@Chinmay-Deo-2004 please share the ss of  the changes

**Comment by Chinmay-Deo-2004** [comment]
> @Chinmay-Deo-2004 please share the ss of the changes

Here's the screenshot of the changes:
Screenshot 2023-04-01 182414

**Comment by Vikash-8090-Yadav** [comment]
Great !!

**Pull request merged**
