### PR TITLE
Logout Button overflow #142 Fixed

### PR DESCRIPTION
**Pull request by 9520prashant**
Now Logout Button is not overflow from right side you can see the change in Screen Shot Below:

Screenshot (285)

### CODE REVIEW

**Review by Vikash-8090-Yadav — DISMISSED** [review]
LGTM

**Comment by Vikash-8090-Yadav** [comment]
Issue Number ?

**Comment by 9520prashant** [comment]
> Issue Number ?

#142

**Review by roshangeorge97 — APPROVED** [review]

**Comment by Vikash-8090-Yadav** [comment]
@9520prashant solve the conflct

**Comment by 9520prashant** [comment]
> @9520prashant solve the conflct

Resolved

**Comment by Vikash-8090-Yadav** [comment]
> > @9520prashant solve the conflct
> 
> Resolved

Chk once. Still not resolved.

**Comment by 9520prashant** [comment]
> > > @9520prashant solve the conflct
> > 
> > 
> > Resolved
> 
> Chk once. Still not resolved.

please check now

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
