### PR TITLE
Updated filters and cards in Pay Salary Section

### LINKED ISSUE #67: Updating the Pay Salary Section with updated UI
The UI of the pay salary section can be improved by using some neumorphism in the cards and making the text more readable
I am a frontend developer and I would like to contribute to this issue under GSSOC'23
I request you to please assign me this issue
image

### PR DESCRIPTION
**Pull request by SakshiShah29**
Closes #67
I have updated the Ui of the Pay Salary Section by adding some animations and neumorphism effects
Updated Ui:
image

Recorded Video:
https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/65860201/4cb6b815-1d00-413e-8bb1-a14b6d1ca118

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@roshangeorge97 Please review  this once.

**Comment by Vikash-8090-Yadav** [comment]
Hey ur deployment is failing, Please check by running `npm run build`

**Comment by SakshiShah29** [comment]
@Vikash-8090-Yadav I have made the corrections. Please let me know if any other change is needed.

**Comment by Vikash-8090-Yadav** [comment]
Please check the responsiveness also the card design is not matching with the Sal-Dapp application .I will share u the refrence tmrw. Please remind me once after 9 pm . Thanks !!

**Comment by SakshiShah29** [comment]
> 

@Vikash-8090-Yadav Can you share the reference for the same so I can work on updating the UI accordingly?

**Comment by SakshiShah29** [comment]
@Vikash-8090-Yadav Please share the references so I can start working on it.

**Comment by Vikash-8090-Yadav** [comment]
Just try to make like the above not exactly same but don't make so fancy i need simole design card . make the pic in rectangular instead of circle . all things are same as original but in ur design that looks so i mean very fancy and childish one make it simple . Hope u understand 🚀

**Comment by SakshiShah29** [comment]
Okay working on it !

**Pull request closed without merging**
