### PR TITLE
Design Happy Client Feature

### PR DESCRIPTION
**Pull request by coder12git**
I have designed the "Happy Client ", according to the designs provided!!
Screenshot 2023-07-20 152636

### CODE REVIEW

**Comment by coder12git** [comment]
@Vikash-8090-Yadav Please review this PR

**Comment by Vikash-8090-Yadav** [comment]
Can this become automatic sliding of the 4-5 seconds gap?

**Comment by coder12git** [comment]
> Can this become automatic sliding of the 4-5 seconds gap?

Ig, that's fine

**Comment by coder12git** [comment]
> Can this become automatic sliding of the 4-5 seconds gap?

Done @Vikash-8090-Yadav , please check

**Comment by Vikash-8090-Yadav** [comment]
Great. Thanks!

**Pull request merged**
