### PR TITLE
Improved Card, Button Style and Navbar

### PR DESCRIPTION
**Pull request by ojasaklechayt**
Issue Number: #147 
 
I have improved some UI like button, navbar and card as I have shown below.

Before Changes:

image

After Changes:

image

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Please share the image before updation.

**Comment by Vikash-8090-Yadav** [comment]
Please share the image before updation.

**Comment by ojasaklechayt** [comment]
> Please share the image before updation.

Done ser

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Review by roshangeorge97 — APPROVED** [review]

**Pull request merged**
