### PR TITLE
Added scroll to top option

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Added scroll to top option in the left side as right side has an image option so not to collapse with that added to right side. It is responsive and will only be visisble when you are not at top.

### At top
Screenshot (16)

### Not at top
Screenshot (17)

### CODE REVIEW

**Comment by Deepanshu0703** [comment]
This is issue #83  assigned to me

**Comment by Vikash-8090-Yadav** [comment]
make this slight to the left  side and  change the  bg colour from black to other. And make the size small of both animation  and part which contains it. Thank uh!

**Review by Vikash-8090-Yadav — CHANGES_REQUESTED** [review]
Do the changes.

**Comment by Deepanshu0703** [comment]
I have changed the color and the position (slightly to the left) 
image

**Comment by Deepanshu0703** [comment]
Please see this PR @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Issue No??

**Comment by Deepanshu0703** [comment]
#83

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
