### PR TITLE
Resolved the bug of Google Github Button

### PR DESCRIPTION
**Pull request by Agrawal-Ayush-009**
I have resolved the Issue of Google-GitHub Button, in which I have separated the functionality of both the  buttons, so now on clicking the Google Button Google Login opens and on clicking the GitHub button GitHub Login opens

Screenshot 2023-06-08 143023

Merge This Under GSSoC'23.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Issue No??

**Review by roshangeorge97 — APPROVED** [review]

**Comment by Agrawal-Ayush-009** [comment]
@Vikash-8090-Yadav Sir, is my PR OK? Please review it and Merge it under GSSoC'23

**Review by roshangeorge97 — APPROVED** [review]

**Comment by Agrawal-Ayush-009** [comment]
@roshangeorge97 @Vikash-8090-Yadav @rrsingh11 Please add Level Tag while merging

**Comment by roshangeorge97** [comment]
Level Tag has been added

**Comment by Vikash-8090-Yadav** [comment]
Thanks @Agrawal-Ayush-009.

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
