### PR TITLE
Centered Take Help Section

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
## Issue
Closed Issue : #162 

## Description 
I have centered the Take Help Section on the website

## Screenshots
image

Please review and merge it under GSSOC'23

### CODE REVIEW

**Review by roshangeorge97 — APPROVED** [review]

**Comment by Swapnil-Singh-99** [comment]
@sarthkdobriyal @Vikash-8090-Yadav 
Please review and merge this PR

**Comment by Vikash-8090-Yadav** [comment]
Hey can u please share the original and updated ss

**Comment by Vikash-8090-Yadav** [comment]
I would recommended to centers the full UI OF THE HELP SECTION AND IMPROVE THE RESPONSIVENESS AS WELL

**Comment by Swapnil-Singh-99** [comment]
Ok I will work on it

**Comment by Swapnil-Singh-99** [comment]
I have made changes to the code and made responsive help section

##Screenshots

image
image
image

@Vikash-8090-Yadav Please review and merge it

Please also add Level label to count it in GSSOC'23

**Comment by Swapnil-Singh-99** [comment]
@Vikash-8090-Yadav @sarthkdobriyal Please review and merge this PR

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM

**Pull request merged**
